### PR TITLE
fucking delete it all

### PR DESCRIPTION
**Pull request by alii**

### CODE REVIEW

**Review by benja — CHANGES_REQUESTED** [review]
HEY Alistair,

Looks like you forgot `.git` in this precious PR.

Regards,
Benja

**Comment by alii** [comment]
OKAY

**Review by alii — COMMENTED** [review]
j

**Comment by benja** [comment]
Alistair, after merging your PR all the code is now gone.

Why is my code?

**Comment by alii** [comment]
canot delete it

**Pull request merged**
